#+title:     UNH Libraries Primo VE Development Environment
#+author:    Jay L. Colbert
#+email:     jay.colbert@unh.edu

* Table of Contents :toc_3:noexport:
- [[#introduction][Introduction]]
- [[#structure][Structure]]
- [[#installation][Installation]]
  - [[#prerequisitespersonal-configuration][Prerequisites/Personal Configuration]]
  - [[#using-literate-programming][Using Literate Programming]]

* Introduction
* Structure
* Installation
Ex Libris provides decent documentation for getting the development environment set up: https://github.com/ExLibrisGroup/primo-explore-devenv

However, they give no documentation for using common options that third-party packages use/require, such as the =--browserify= flag when using =gulp=.
Here is how I set up my development environment exactly how I have it, step by step.

** Prerequisites/Personal Configuration
*Install Homebrew*

I have a MacBook Pro, and I use Homebrew to manage my packages.
Run the following in your terminal:
#+begin_src shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#+end_src

*Install the iTerm2 terminal emulator*
#+begin_src shell
brew install --cask iterm2
#+end_src

*Install the fish shell (optional)*
   
I like fish as opposed to bash or zsh.
This step is optional, but the way I will eventually install =nvm= will differ from the way you do if you use bash or zsh.
If you use fish, make sure to make it your default shell: https://fishshell.com/docs/current/tutorial.html#switching-to-fish
#+begin_src shell
brew install fish
#+end_src

*Install NVM*
   
Because I use the fish shell, I will do this differently than you will if you use bash or zsh.
If you are using something that isn't fish, follow these instructions: https://github.com/nvm-sh/nvm#installing-and-updating

If you /are/ using fish, then install the =nvm.fish= Fisher plugin by running this in the command line:
#+begin_src shell
fisher install jorgebucaran/nvm.fish
#+end_src

Then you'll need to install the *latest stable release* of Node.js:
#+begin_src shell
nvm install latest
#+end_src

Set the default version:
#+begin_src shell
set --universal nvm_default_version lts
#+end_src

*Install gulp globally*
#+begin_src shell
npm install -g gulp
#+end_src

*Install yarn globally*
#+begin_src shell
npm install -g yarn
#+end_src

** Using Literate Programming
