#+title:     UNH Libraries Primo VE Development Environment
#+author:    Jay L. Colbert
#+email:     jay.colbert@unh.edu

* Table of Contents :toc_3:noexport:
- [[#introduction][Introduction]]
- [[#structure][Structure]]
- [[#installation][Installation]]
  - [[#prerequisitespersonal-configuration][Prerequisites/Personal Configuration]]
  - [[#development-environment][Development Environment]]
    - [[#yarn][Yarn]]
    - [[#formatting-and-linting][Formatting and Linting]]
  - [[#configuration][Configuration]]
    - [[#gulpfile][Gulpfile]]
    - [[#colors][Colors]]
  - [[#using-literate-programming][Using Literate Programming]]

* Introduction
* Structure
* Installation
Ex Libris provides decent documentation for getting the development environment set up: https://github.com/ExLibrisGroup/primo-explore-devenv

However, they give no documentation for using common options that third-party packages use/require, such as the =--browserify= flag when using =gulp=.
Here is how I set up my development environment exactly how I have it, step by step.

** Prerequisites/Personal Configuration
*Install Homebrew*

I have a MacBook Pro, and I use Homebrew to manage my packages.
Run the following in your terminal:
#+begin_src shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#+end_src

*Install the iTerm2 terminal emulator (optional)*
#+begin_src shell
brew install --cask iterm2
#+end_src

*Install the fish shell (optional)*
   
I like fish as opposed to bash or zsh.
This step is optional, but the way I will eventually install =nodejs= will differ from the way you do if you use bash or zsh.
If you use fish, make sure to make it your default shell: https://fishshell.com/docs/current/tutorial.html#switching-to-fish
#+begin_src shell
brew install fish
#+end_src

*Install ASDF*

=asdf= is a tool version manager.
It can replace other tool version managers such as =nvm=.
Because I use the fish shell, I will install =asdf= differently than you will if you use bash or zsh.
If you are using something that isn't fish, follow these instructions: https://asdf-vm.com/guide/getting-started.html#_1-install-dependencies

If you /are/ using fish, then install the =asdf= oh-my-fish plugin by running this in the command line:
#+begin_src shell
omf install asdf
#+end_src

Then you'll need to install the *latest release* of Node.js:
#+begin_src shell
asdf plugin add nodejs
asdf install nodejs latest
#+end_src

Set the default version:
#+begin_src shell
asdf global nodejs latest
#+end_src

*Install gulp globally*
#+begin_src shell
npm install --global gulp-cli
#+end_src

*Install yarn globally*
#+begin_src shell
asdf plugin add yarn
asdf install yarn latest
asdf global yarn latest
#+end_src

*Install Visual Studio Code*
#+begin_src shell
brew install --cask visual-studio-code
#+end_src

** Development Environment
*In a new terminal window*, =cd= into the cloned directory.
#+begin_src shell
cd /path/to/primo-explore-devenv
#+end_src

*** Yarn
I use yarn instead of npm for installing node packages.
With yarn, you need to update the version on a project level;
this means the version of yarn in your project will be higher than your global version.
#+begin_src shell
yarn set version berry
#+end_src

You'll want to keep the node modules folder, though, so create a =.yarnrc.yml= file:
#+begin_src shell
touch .yarnrc.yml
#+end_src

(Eventually, I will figure out how to use yarn without the node modules in the Primo development environment. I think it involves fiddling around with the gulp tasks.)

And add the following:
#+begin_src yaml
nodeLinker: node-modules
#+end_src

Finally, in the command line, use yarn to install the node packages:
#+begin_src shell
yarn
yarn install
#+end_src

*** Formatting and Linting
In order to keep things tidy, I use a combination of formatters and linters.

**** Prettier
I use Prettier purely for formatting, not for syntax.
#+begin_src shell
yarn add --dev --exact prettier
#+end_src

Note: instead of ~install --save-dev~, yarn uses ~add --dev~.

Create a =.prettierrc= file:
#+begin_src shell
touch .prettierrc
#+end_src

And at minimum put in an empty pair or curly brackets.
This will enforce Prettier's defaults.
#+begin_src json
{}
#+end_src

Finally, create a =.prettierignore= file:
#+begin_src shell
touch .prettierignore
#+end_src

And put in the following so Prettier will ignore all of the code in the =node_modules= folder:
#+begin_src conf
**/node_modules/*
#+end_src

I also install it as a plugin in Visual Studio Code and make it my default formatter, for auto-formatting.

**** ESLint
ESLint is for checking problems in JavaScript code.
#+begin_src shell
yarn add --dev eslint
#+end_src

I like Arctic Ice Studio's JavaScript style guide, so I install their ESLint configuration:
#+begin_src shell
yarn add --dev @arcticicestudio/eslint-config-base
#+end_src

Create an =.eslintrc.js= file:
#+begin_src shell
touch .eslintrc.js
#+end_src

And an =.eslintignore= file:
#+begin_src shell
touch .eslintignore
#+end_src

Put the following in your =.eslintignore=:
#+begin_src conf
**/node_modules/*

!.eslintrc.js
#+end_src

And make sure to install the ESLint Visual Studio Code plugin.

To keep ESLint and Prettier from clashing, do the following:

Install =eslint-config-prettier=, =eslint-plugin-import=, and =eslint-plugin-prettier=
#+begin_src shell
yarn add --dev eslint-config-prettier eslint-plugin-import eslint-plugin-prettier
#+end_src

And add the following to your =.eslintrc.js=:
#+begin_src javascript
module.exports = {
  extends: [
    /* Provides support for all ESLint core rules. */
    "@arcticicestudio/eslint-config-base",
    /*
     * Optional entry point to enable support for projects using Prettier.
     * Note that this must always be placed after the `@arcticicestudio/eslint-config-base` preset to take precedence,
     * otherwise it won't prevent errors due to useless and possibly conflicting rules!
     */
    "@arcticicestudio/eslint-config-base/prettier",
  ],
  plugins: ["import"],
  rules: {
    "import/no-extraneous-dependencies": [
      "error",
      {
        devDependencies: ["**/*.js"],
      },
    ],
  },
};
#+end_src
** Configuration
*** Gulpfile
First, we need to install gulp in our development environment.
#+begin_src shell
yarn add --dev gulp
#+end_src

Then, test the version.
#+begin_src shell
gulp --version
#+end_src

#+RESULTS:
| CLI   | version: | 2.3.0 |
| Local | version: | 4.0.2 |

Ex Libris' =primo-explore-devenv= package has =gulpfile.js= separate from the gulp directory and tasks.
However, you can actually combine these!
*** Colors

** Using Literate Programming
